version: '3'

services:
  demo:
    build: .
    command: ng serve --host=0.0.0.0
    ports:
      - "4200:4200"
    volumes:
      - type: bind
        source: .
        target: "/projects"
    tty: true
    depends_on:
      - lib
  lib:
    build: .
    command: sh ./scripts/build_lib.sh
    volumes:
      - type: bind
        source: .
        target: "/projects"
    tty: true
    healthcheck:
      test: ["CMD-SHELL", "check_health.sh"]
      interval: 1s
      timeout: 10s
      retries: 10
