version: '3'

services:
  node:
    build: .
    command: ng serve --host=0.0.0.0
    ports:
      - "4200:4200"
    volumes:
      - type: bind
        source: .
        target: "/projects"
    tty: true
